### ISSUE TITLE
Feature Request: Add more backup options

### ISSUE THREAD

**Issue by librethanks** [breez/breezmobile#1122]
Some people don't want to or can't use  google, nextcloud, or webdav.

I understand that channel state has to be maintained for proper backups, but I think the current backup options are lacking. Perhaps adding a feature to make a local backup that gets saved each time the app is opened or the channel state changes which the user can then choose how to backup on their own. Perhaps using something like syncthing or other file synchronization integration.

**Comment by kingonly** [comment]
Thank you for your feedback, but any local backup won't solve the basic use cases in which backup is needed in the first place which are lost, broken devices. Android doesn't not provide an interface to its file sync mechanism, so because of that and because backup doesn't happen in real time, it's not a viable solution. 

We have A LOT of experience after 4 years of Breez in the market. The reality is that most users are happy with Google/iCloud and the product can cater everyone's need.

Moreover, we will soon release another product where the backup is stored on the node itself w/o 3rd party cloud dependency.
