### ISSUE TITLE
Can't install on my Samsung Galaxy S7

### ISSUE THREAD

**Issue by philippgille** [breez/breezmobile#118]
I joined the beta program on Google Play, but I can't find the app on my device's Play store, and when viewing the app on the Play store's website, I can select a device to install the app to, but only my Samsung Galaxy S9 is selectable, but not my S7.

I found this other issue that sounds related: https://github.com/breez/breezmobile/issues/83
But in my case the S7 *does* have a 64bit SoC.

Is there any other reason why I'm not able to install Breez on my device? Maybe because it's Android 6?

In any case, this should be documented somewhere on the website or the GitHub repo. Like some note that says that 64bit etc. are required.

**Comment by kingonly** [comment]
We require Android 7 and above 64bit.
You're write, we'll add it to our readme.

**Comment by philippgille** [comment]
Fixed in d1dc79d50c94d17d4d336eb0f2dda5e9eede21da

**Comment by petrkr** [comment]
Any technical reason why you force 64bit Android? Lot of cheap phones or terminals are still on 32bit CPU or Android (even Android 10).


Other wallets works fine, but they does not have POS mode required for restaurants.

**Comment by kingonly** [comment]
It just requires more resources (build and QA). We decided not to invest in it because 32bit is deprecated and probably gone soon (https://www.androidauthority.com/arm-32-vs-64-bit-explained-1232065/).

**Comment by petrkr** [comment]
So it's more political decision than technical. Sad... that means we can not use old phones (or even cheap new) for this only one purpose. It's hard to overtalk those peoples to accept bitcoin at all. And if I tell them, they need tripple priced phone, because community decided, they will refuse it to use...

Anyway thanks for answer. I have to do it another way for those use-cases.


Or maybe, if you have problem with resources, is there way how I can rebuild it myself?

**Comment by kingonly** [comment]
Nothing political about it. Resource allocation based on technical information. We're not building for now, we're building an infrastructure for the not so distant future. However, Breez is open source and we welcome external contributions. Again, it's not just dev, it's QA. As for your question, that's part of the work that is needed. We only build 64bit right now.

**Comment by petrkr** [comment]
Sorry, I already contribute other projects in my free time. If I will contribute for free everyone who write that, I will not do anything else whole day.. But I also need to pay rental fees, so I have to do paid jobs instead. This is your project, you know it much more than me and if there is way how I can do it myself, it is faster to ask...

For now this SW is unusable on most cheap terminals and phones, because they still use Mediatek 32bit CPU. So I have to find another way, because those peoples will really not buy new phone for 100+ USD just because one app.

Anyway thanks for your time. I hope there will be someone who will understand needs of bitcoin meaning and try to do it more wide... Like blockstream did satellite downstream of blockchain and stick done sending transactions over SMS services (so peoples can use even old Nokia 5110).

You goes way to use most recent expensive hardware, it was your decision, but most of peoples still use 5 years old phones which was NOT expensive those days, so it's also some mediatek or old arm based ones...

Again thanks for your time... I will add this to my "what I want contribute" list, but already have more than 20 project right now.
