### ISSUE TITLE
Did not get a refund

### ISSUE THREAD

**Issue by MrManPew** [breez/breezmobile#326]
Hi,
I added too much fund to my account (more than 900,000) and I tried to do a refund, Breez stated that  it was broadcasted, but I did not get the BTC? also I restarted the app and now I can not see any info about the refund. 
What should I do? How can I see details about my refund?

By the way, when doing a refund, it should show you the transaction id, so one can track the refund...

Thanks

**Comment by kingonly** [comment]
Please send an email with your logs to contact@breez.technology (Advanced> Developer screen> top right menu> Share Logs) and we'll take a look. Typically, the when the tx is broadcasted, it is trackable via the destination address so there's no need to add a UI in Breez for it.
This forum is for generic issues, not for support, so closing the issue here and we'll continue the support via email.
