### ISSUE TITLE
Backup without google

### ISSUE THREAD

**Issue by tifDev** [breez/breezmobile#432]
While other backups forms are not yet implemented, can I somehow do a local backup ? Like backing up/copy the files from the app to my pc?

Thanks

**Comment by kingonly** [comment]
You can use 'Export DB Files' from Developers screen top right menu and use the in own lnd instance, but this is an error prone process and not practical as you need to export after every single transaction. So, we don't "officially" support it. We'll add more cloud providers.
There's no privacy issue with using Google when applying an additional encryption key.

**Comment by Chris869218** [comment]
If someone switches their backup location from iCloud to google drive, then later downloads Breez on a different iOS device and the default starts out as iCloud, is there a risk of unknowingly broadcasting an old channel state and losing funds? Or when the switch from iCloud to Google Drive backups is made, is the iCloud backup deleted?

**Comment by kingonly** [comment]
There's no "default" in restore. We don't currently delete the iCloud data. There's no risk in losing funds (the client won't try to broadcast the old state), but the channels will get closed by the peer in this case.

**Comment by blacklightpy** [comment]
There's still a risk if Google suddenly bans your account one day. It has happened to some people before. So it's kind of a custodial solution for now, so should it be the default solution in a non-custodial wallet? Many other apps offer on device backups too, like WhatsApp. Isn't that simpler to implement than Google Drive?

**Comment by kingonly** [comment]
Custodial means access to funds, not 3rd party dependency. Keep in mind the following:
1. Lightning requires a backup after every payment.
2. On-device backup doesn't help with the basic use cases of lost, stolen or broken device.
3. Breez allows you to manually export your lnd files.

We will offer more backup solutions (dropbox, NextCloud etc).

**Comment by blacklightpy** [comment]
But here, using a 3rd party dependency just transfers the custody to someone else. I understand that you don't want users to be dependent on Breez, but this makes users dependent on Google Drive instead. The point of a non-custodial wallet is not only that it cannot access the keys, but also that users should be able to access the funds without the help of a 3rd party.

You could just store an encrypted backup in a dedicated Breez folder just like how WhatsApp does. BLW does exactly this. Eclair also does the same thing, but with local backup being compulsory and Google Drive backup as an optional choice.

You said Whatsapp only allows GD backups. That's because it makes local backups and then uses Google Drive backups as an additional backup. The backups are stored in /sdcard/Whatsapp/Databases. There are 8 backups which correspond to the last 8 days.

> On-device backup doesn't help with the basic use cases of lost, stolen or broken device.

Even Google Drive backup won't help in case of a stolen device. Because the Breez wallet will be installed in the device anyways. In case of a lost device it will help, but the point is to give the user a choice. It's not Breez's fault that he lost the device. Breez gave him both choices of local backup and GD backup for convenience. Similary for a broken device, but here a user can copy the backup if it was stored in an SD Card.

The point is to let the users decide which 3rd party they have to trust to store their channel states. I'm sure Google won't steal the funds in anyway, but like I said, they could ban your account instead. And of course it's great to support other services liike Nextcloud, but it's still missing out on the basic aspect of self-custody.

> Other Lightning solutions create an even greater dependency.

But not all of them. For example, look at Muun. They use submarine swaps to settle onchain, and store funds in a 2-of-2 multisig and store only one key on device. Then they give you a file containing the encrypted keys which you have to decrypt with a recovery code and then you can access your funds without any other dependency. I don't see any dependencies withh other non-custodial wallets as well.

Also I know we can manually export the lnd files, but it's difficult for the average user to import it to Breez. I don't see why you have to omit this feature and work harder to implement Nextcloud backups etc. Even if say others were worse, why wouldn't you want to have a better UX?

**Comment by kingonly** [comment]
> The point of a non-custodial wallet is not only that it cannot access the keys, but also that users should be able to access the funds without the help of a 3rd party.

Everything is 3rd party. Your CPU, your OS, etc. You're using non-custodial is a much broader term.

> . BLW does exactly this. Eclair also does the same thing, but with local backup being compulsory and Google Drive backup as an optional choice.

Not Phoenix and BLW is not maintained anymore.

> You said Whatsapp only allows GD backups. That's because it makes local backups and then uses Google Drive backups as an additional backup. The backups are stored in /sdcard/Whatsapp/Databases. There are 8 backups which correspond to the last 8 days.

Going into the internals of WhatsApp doesn't make it and end user option...
 
> The point is to let the users decide which 3rd party they have to trust to store their channel states. I'm sure Google won't steal the funds in anyway, but like I said, they could ban your account instead. And of course it's great to support other services liike Nextcloud, but it's still missing out on the basic aspect of self-custody.

I'm with you on that, but it's more of a trust issue than self-custody imo. You are ignoring your ability to use the lnd database that already exists in Breez. 

> But not all of them. For example, look at Muun. They use submarine swaps to settle onchain, and store funds in a 2-of-2 multisig and store only one key on device. Then they give you a file containing the encrypted keys which you have to decrypt with a recovery code and then you can access your funds without any other dependency. I don't see any dependencies withh other non-custodial wallets as well.

Muun doesn't run a Lightning node. They do on-chain swaps. Phoenix backups are store on the Acinq node.
 
> Also I know we can manually export the lnd files, but it's difficult for the average user to import it to Breez. I don't see why you have to omit this feature and work harder to implement Nextcloud backups etc. Even if say others were worse, why wouldn't you want to have a better UX?

"have to omit"? We do what we can... Storing to an SD card is simply isn't a good-enough backup option in our mind, so the our current default is different. 

Breez is an open source project, you are welcome to add PR, fork, etc. We welcome any contribution that benefit our users.

**Comment by blacklightpy** [comment]
> Going into the internals of WhatsApp doesn't make it an end user option...

/sdcard/WhatsApp is not going into the WhatsApp internal folders. /sdcard is the default internal storage folder when you open the File Manager. I always copy my WhatsApp backup folders instead of relying on Google Drive because I have so many media files in it too. Security isn't the issue, accessibility is.

> Everything is 3rd party. Your CPU, your OS, etc. You're using non-custodial is a much broader term.

> I'm with you on that, but it's more of a trust issue than self-custody imo.

But my point is, a Google account can get banned for random reasons. As I said before, accessibility, not security. With a local backup, you have a freedom of choice to backup anywhere. Suppose you're going offline for a month - in that case you'll still have your local backup. The rule of backups is that a backup on your server is better than backup on any online service.

> You are ignoring your ability to use the lnd database that already exists in Breez.

This is still very inconvenient. You have to manually perform a backup. This doesn't help in case the device gets damaged. Most importantly, it makes it more difficult for an average person to import the backup.

> Storing to an SD card is simply isn't a good-enough backup option in our mind

The question is why? It's good that you guys prioritized cloud backups, but isn't it much easier to implement local backups? I'm suggesting that Local+Cloud is the best combination. Storing to local alone isn't a solution even in my opinion.

> Breez is an open source project, you are welcome to add PR, fork, etc. We welcome any contribution that benefit our users.

Thanks, I'll try to contribute if I get free sometime. But the main concern is that you seem opposed to it. Forget about other wallets, it is still something that makes Breez better. 

---

Apparently Eclair keeps backups in the app internal folders. That's not what I was hinting at. I was suggesting a similar structure to WhatsApp as I've mentioned above. That should've caused the confusion. App internal backups are also an inconvenient solution. This should've caused the confusion.

I was actually trying to gift LN satoshis to a friend who probably won't use it in a while, but it was difficult for me to do without relying on a custodian service like Bluewallet. I also needed a simple app, and even though Breez is simple, I can't share the node state (lnd db is still complicated).

**Comment by kingonly** [comment]
> /sdcard/WhatsApp is not going into the WhatsApp internal folders. 

I didn't say "internal folders", I said "internals". WhatsApp doesn't expose it as a primary  backup option.
> Suppose you're going offline for a month - in that case you'll still have your local backup. 

And you still can access the Breez app. Local backup in this use case don't have an advantage over just using the app.

> Breez is an open source project, you are welcome to add PR, fork, etc. We welcome any contribution that benefit our users.

> Thanks, I'll try to contribute if I get free sometime. But the main concern is that you seem opposed to it. Forget about other wallets, it is still something that makes Breez better.

I'm really not opposed to storing in an SD card as a secondary option.
>  I was suggesting a similar structure to WhatsApp as I've mentioned above. 

So I think we're aligned. I'm cool with adding another option to store another backup in an SD card.
 
> lnd db is still complicated.
Not that complicated, but not for average users, true.

**Comment by kingonly** [comment]
Added WebDav support in latest
