### ISSUE TITLE
err=funding failed due to internal error 

### ISSUE THREAD

**Issue by Chris869218** [breez/breezmobile#434]
When I try to open a channel with Breez (https://1ml.com/node/031015a7839468a3c266d662d5bb21ea4cea24226936e2864a7ca4f2c3939836e0) I get the following error: 'funding failed due to internal error.' I've tried with RTL and ZAP, and tried with different amounts. I haven't had problems opening channels with other nodes. Is Breez currently not accepting inbound connections? Any other ideas? Thanks.

**Comment by kingonly** [comment]
Thanks for trying and sorry about the confusion.
We have a 10M sats limit. Managing smaller channels was problematic and caused more payment failures.

Since we're not using minchansize, but we have a custom logic using channel acceptor, this is the error you see (prior to lnd 0.12 there wasn't a way to send custom errors in channel acceptor). This is something we will fix after we upgrade.

**Comment by Chris869218** [comment]
Thanks for the response. I tried increasingly smaller amounts and I got to "channel is too small, the minimum channel size is: 20,000 SAT" so I was thinking that was the minimum and amount wasn't my problem. Appreciate the explanation.

**Comment by kingonly** [comment]
Added error details
