### ISSUE TITLE
Payment Details Dialog UI problem on small display

### ISSUE THREAD

**Issue by sash13** [breez/breezmobile#499]
Hi,

When I expand all fields in Payment Details Alert Dialog some information and ui element move out from rect.
device: Sony Xperia X (display 1080 x 1920 pixels, 16:9 ratio (~441 ppi density))
app: last version from Play Store
![image](https://user-images.githubusercontent.com/105962/122171001-e69eb680-ce87-11eb-8cad-672d72daea71.png)

**Comment by ademar111190** [comment]
It seems the this issue was fixed on 823aa6fc0933e77a3500c614dbb7c5ad8a789c04

**Comment by kingonly** [comment]
You can scroll now?

**Comment by kingonly** [comment]
Yes, it's scrollable now. I'm closing.

**Comment by ademar111190** [comment]
Yes @kingonly , I was working on it and I find a way to simulate the issue through split screen, I did solve it but before opening the MR I did a rebase and to my surprise I had a conflict, so I did run the master without my changes and the bug was gone.

Take a look:


https://user-images.githubusercontent.com/1225438/126006722-13668eac-4492-4170-91af-c05665f9dd50.mp4

Here how it looks like before that commit:


https://user-images.githubusercontent.com/1225438/126006980-876f12ef-1309-402f-a37b-738c5e59246f.mp4
