### ISSUE TITLE
Cannot send payment through any route

### ISSUE THREAD

**Issue by yuvadm** [breez/breezmobile#517]
I'm testing breez payments with an LN node that is directly peered and has an open channel to [Breez](https://amboss.space/node/031015a7839468a3c266d662d5bb21ea4cea24226936e2864a7ca4f2c3939836e0).

When scanning invoice and attempting to pay, the payment never goes through, not directly nor via any other route.

The server seems to be attempting to resolve `03988685d49e68b5d855c3403d3f8b5120dcbbe89973dbf4e57c2102538f2fc30d` which is an unknown public key.

Requesting a route to this node from Breez also returns an `UnknownNextPeer` error.

**Comment by kingonly** [comment]
Just to clarify: you are trying to pay from the node?
Why do you think this issue is related to Breez?
If it's an lnd node, try resetmc and then queryroute.

As for Breez, debug using: https://github.com/breez/breezmobile/wiki/Troubleshooting-Payment-Failures
UnknownNextPeer might suggest the Breez-node channel isn't in the client graph. Maybe a private channel or there wasn't a graph update.

**Comment by yuvadm** [comment]
Since Breez issued the invoice, I would expect it to show a well known node that is accepting the payment.

Is this public key expected? None of the LN explorers seems to recognize this pubkey.

**Comment by kingonly** [comment]
There's a private channel between Breez and Breez mobile. That's the reason explorers are not showing mobile nodes. That's the "right" topology in case a node is offline most of the time and cannot participate in routing.  Routing should be executed using routing hints in these cases.

**Comment by yuvadm** [comment]
Ok I had no idea Breez runs two nodes. So just to clarify if I have a route to `Breez` AKA `031015a7839468a3c266d662d5bb21ea4cea24226936e2864a7ca4f2c3939836e0@212.129.58.219:9735` I should be able to route through that (via private channel)  to the elusive `03988685d49e68b5d855c3403d3f8b5120dcbbe89973dbf4e57c2102538f2fc30d`?

**Comment by kingonly** [comment]
Breez mobile app runs a node. That's your node.
Breez company runs a hub (0310).
Breez hub and Breez node are connected via a private channel. This channel information is included in the invoice routing hints since it's not a part of the Lightning graph.

When a sender is trying to pay Breez mobile, it should calculate the route using the graph information and the invoice routing hints. That's the reason all the Breez mobile apps are able to receive payments.

**Comment by yuvadm** [comment]
Thanks for the clarification regarding the mobile node, that makes much more sense to me now.

However, it still doesn't seem the routing hints are helping out since my node still can't resolve a path to the mobile node, not even if I explicitly route the payment out through `Breez`.

For debugging, I also added my node as a peer directly to the mobile node (via the developers menu), but that didn't help either.

**Comment by kingonly** [comment]
"it still doesn't seem the routing hints are helping out since my node still can't resolve a path to the mobile node": that's an issue with your node then... If it gets the channel information via routing hints, it should use it to calculate the route. Maybe it's lnd mission control that black listed this channel, idk. But again, it doesn't seem to be a Breez related issue.

You can also connect to your mobile node directly: https://github.com/breez/breezmobile/wiki/Opening-Channels

**Comment by yuvadm** [comment]
Cool thanks for your help @kingonly and for all the info, I'll keep digging into the routing on my side
