### ISSUE TITLE
Once Active Manager Password is enabled under POS setting, user can access Preferences --> Security & Backup without requiring a password 

### ISSUE THREAD

**Issue by wksantiago** [breez/breezmobile#528]
Once Active Manager Password is enabled under POS setting, user can access Preferences --> Security & Backup without requiring a password.

Should this area be restricted?  Since it gives user the ability to create a PIN and activate it, locking the Manager out.

**Comment by kingonly** [comment]
This is by design. We think users should be able to have a pin, even if there's manager password set.
Users can also uninstall the app, locking the manager out. Manager password isn't aimed to cover all of the scenarios, but to offer a protection from employees that are tempted to transfer funds out.

**Comment by kingonly** [comment]
On the other hand, the manager can set the pin.

**Comment by wksantiago** [comment]
Great good to know and this explanation makes sense.

Thanks,

William K. Santiago
***@***.******@***.***)

[Website](https://privkey.io/) | [LinkedIn](https://www.linkedin.com/in/wksantiago/) | [Twitter](https://twitter.com/WilliamSantiago)

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by kingonly** [comment]
I actually want to protect this screenshot with the manager password also, so reopening...

**Comment by kingonly** [comment]
Fixed in latest, package is rolling out today.
