### ISSUE TITLE
iOS: standard go back gesture doesn't work (or unimplemented)

### ISSUE THREAD

**Issue by Kixunil** [breez/breezmobile#592]
This was reported by a friend who I talked to over text messages and I don't have iOS phone so I may not be perfectly accurate in description. He explained that there's some kind of "go back" gesture in iOS that is a replacement for back arrow on Android. According to him it does not work in Breez and is quite annoying as iOS users tend to use the standardized ways of interacting with apps.

**Comment by erdemyerebasmaz** [comment]
That gesture is app-specific and is not standardized behavior.

It would be unusable because it would interfere with opening the drawer on most pages on our app. For the pages that do not have a drawer, taking our users habitual behavior consideration, we believe it will cause us & our users more headaches. e.g., it would lead to users navigating back to previous page by mistake, losing information etc.

Closing.
