### ISSUE TITLE
I added funds through Bitcoin on-chain but i don't see them

### ISSUE THREAD

**Issue by Perlover** [breez/breezmobile#87]
Hi,

I have Android 9, last Breez version from Google Market

I clicked "Add funds" , got Segwit address from Breez and sent on-chain bitcoins there. The Breez noticed me about receiving and after about confirmed. But balance showed me only few satoshies from channel. In Developer tab i run walletbalance and see zeroes.

What happens? How can i restore keys for example? I don't have the seed because you don't show it to users.

**Comment by kingonly** [comment]
Hi there,

The funds added through the Submarine Swaps address is not transferred to the underlined wallet, but to the your end of the channel.
In cases the Submarine Swap ln tx fails or you sent more funds than the limit, you will be able to redeem your funds after 24 hours. 
If you want us to help debug what happened in your case, suggest we move this to DM via Twitter or mail since we'll need to get the tx information and maybe logs from the product.

**Comment by Perlover** [comment]
Thanks for answer. Now the transaction has 78 confirmations. Ok, i will wait 144 confirmations.

But it's way is very strange for user experience... You have the lnd inside and lnd has wallet inside but you generates address for swap....

**Comment by kingonly** [comment]
Thanks for the feedback. We understand it's an unorthodox approach. 
Breez is designed ad a Lightning-only client, that's the reason we use Submarine Swaps. We think removing the need to manage a bitcoin wallet simplifies UX.
The underlined wallet is only used in case of the user is closing the channel.

**Comment by Perlover** [comment]
I understand your concept.
In your wallet i can have only channel through your node. You created inbound channel to me by auto. And i cannot create myself channel. For funding i should use Submarine Swap so when i will be funded your lightning fees will be applied...

So you want to be like "bank" and you want to chain your users to yourself. All payments through your node, in & out payments through your node.

I will recommend your wallet to nobody.

Good luck!

**Comment by Perlover** [comment]
> user is closing the channel.

How can i close channel?
I don't see same option. I see only "Remove funds" but there are again Submarine Swaps

**Comment by kingonly** [comment]
Not at all what we want to accomplish... 
We're thinking of ways to improve UX without compromising security and privacy.
That's why we expose all of lnd functionality (including opening and closing channels) in our developer screen.
In the very near feature we will allow user to choose their hub... 
It's ridiculous to think we're want to make money of ln tx fees. On the contrary, we put money in creating channels and executing on-chain tx via Submarine Swaps.

**Comment by Perlover** [comment]
> In cases the Submarine Swap ln tx fails or you sent more funds than the limit, you will be able to redeem your funds after 24 hours.

I saw log file of Breez
Yes, there is reached limit (i didn't know about this)

So when 144 confirmation will be passed what will be next?

I sent bitcoins from Electrum wallet to Breez. I will get there back (to Eclair)? Or i will get them into on-chain wallet of Breez? How will the redeem process take place?

**Comment by kingonly** [comment]
You will see a 'Refund' menu item and you will able to transfer the funds to any address you choose.

**Comment by Perlover** [comment]
@kingonly Thanks! I got refund and already sent this to my other segwit address.
